language: python

cache: pip

jobs:
  include:
    - os: linux
      python: 3.5
      env: TOXENV=py35

    - os: linux
      python: 3.6
      env: TOXENV=py36

    - os: linux
      python: 3.7
      env: TOXENV=py37

    - os: linux
      python: 3.8
      env: TOXENV=py38

    - os: linux
      python: 3.9-dev
      env: TOXENV=py39

    - os: linux
      python: 3.7
      env: TOXENV=cov
      after_success:
        - travis_retry pip install coveralls
        - coveralls

    - os: osx
      language: generic
      env: TOXENV=py37

  allow_failures:
    - os: linux
      python: 3.9-dev
      env: TOXENV=py39

install:
  - travis_retry bash -x .travis/install.sh

script:
  - tox -- --md-report-color text

notifications:
  slack:
    secure: NfS1a6caCCDIgC/1MgNqD8e3IR9E5lKn8VA5KsdY8hBxYXHEYxZ52DaX+fIDifW5Pz7QG0NMHUfn5OiAbJOtRDqFLt0DN/cgzMoN4E+obhRzWx6JhYBMHQTE2qe7LnzIqmnWHoYP2K0HUcnyRMp8teIw8To89LwkyVD6G9oMlERCtTGzORpwtqPJKeNrjkDA2fbmlmca4HI0BCbkl8aWVfNvdEka/z09s/XzkMYbuhpJWnyFfARDQS5zmdZCEtWUbQbQsWvl9z+d2JISgzYzrQOIV9f8BFZTvPq6KUlsnPpR8O3nBr5Q61i51awd8HhH6zjn8jKoJVLdrjt1HPSWgWZx/BUqGKBa6PVrkZVwOQx+eNYyCIYEv38ViYAayO6c5Yt/LCsNg2h4Nyl6UM7OwTEN6Z+L1+ke70mWnmRHvYdIBbszvkF6H6BRF+1Yj//Yr7fx33yXzKEhIIyZ94zbwu6YqdPhuROSIHv5lCe5+dT8uYWNNF0QH46GcWC9/2kapO1ySu3iBOFzPxyDnxaBzzqazARKl/fibpbnMvzyKZnd1moHrWGSePKzF5ynGSxSzxctSf7Da683dl3jmqBUcTsDP7IEcj6LkJCF2/Q8ZexX6Kn0zULP+QNOisdt89gHFjHHA6PUD4g7qWXWsB/8y51HUtW7EiaoLjsAdaAHN8w=
