language: python

matrix:
  include:
    - python: 2.7
      env: TOXENV=python2.7
    - python: 3.3
      env: TOXENV=python3.3
    - python: 3.4
      env: TOXENV=python3.4
    - python: 3.5
      env: TOXENV=python3.5
    - python: 3.6
      env: TOXENV=python3.6

os:
  - linux

install:
  - pip install tox
  - pip install coveralls

script: 
  - tox
  - python setup.py test --addopts "-v --cov datetimerange --cov-report term-missing"

after_success:
  - coveralls

notifications:
  slack:
    secure: NfS1a6caCCDIgC/1MgNqD8e3IR9E5lKn8VA5KsdY8hBxYXHEYxZ52DaX+fIDifW5Pz7QG0NMHUfn5OiAbJOtRDqFLt0DN/cgzMoN4E+obhRzWx6JhYBMHQTE2qe7LnzIqmnWHoYP2K0HUcnyRMp8teIw8To89LwkyVD6G9oMlERCtTGzORpwtqPJKeNrjkDA2fbmlmca4HI0BCbkl8aWVfNvdEka/z09s/XzkMYbuhpJWnyFfARDQS5zmdZCEtWUbQbQsWvl9z+d2JISgzYzrQOIV9f8BFZTvPq6KUlsnPpR8O3nBr5Q61i51awd8HhH6zjn8jKoJVLdrjt1HPSWgWZx/BUqGKBa6PVrkZVwOQx+eNYyCIYEv38ViYAayO6c5Yt/LCsNg2h4Nyl6UM7OwTEN6Z+L1+ke70mWnmRHvYdIBbszvkF6H6BRF+1Yj//Yr7fx33yXzKEhIIyZ94zbwu6YqdPhuROSIHv5lCe5+dT8uYWNNF0QH46GcWC9/2kapO1ySu3iBOFzPxyDnxaBzzqazARKl/fibpbnMvzyKZnd1moHrWGSePKzF5ynGSxSzxctSf7Da683dl3jmqBUcTsDP7IEcj6LkJCF2/Q8ZexX6Kn0zULP+QNOisdt89gHFjHHA6PUD4g7qWXWsB/8y51HUtW7EiaoLjsAdaAHN8w=

deploy:
  provider: pypi
  user: vmmhypervisor
  password:
    secure: eaor4qJ/fbeqyciJGUCqSrCl6jY5RDjwFk/wQpLJvAMujtTs2ye7qpCAVyEdlYFg3Wy7LJGqrW0vSxzwIRkBz8587UydpbhccfkUPjON7xNwVdC1jKk/YJNW8CWIa26UF77Jz7Hd1UGKzS3UQcXXa9KiZQi6WT6ME+4NF4H9x5jT4y8VeteVKLLNwxbdVQsrPEK1GrS/VUBTSgdI2cVV7PqVJQ7B9ija7OrSNol35sUbwA8bEfMloY3GVCsxLJp8B8AdTc+9EWmeheRl88mExyLdlvg1hMrzUjmmix0DbBIzORHOxA5VrWzHecnN2tI0XqYY3l1kmUvPehlnaOP3Jfpu5hXs0NRXjDJ9fRZUQQ1swyObzcg7dXqTx/qK/LCdWgd1We+wMf3CIja1GMNxP9xBxsvWBw7w3naTkS4uMR9if5eJfrf76umNj+xOSlopvHTmlvmkD5dLy7mSIzIqj4GqzsY/WeECZVnnjOubY5+r/06e1TC92RJE/3C2N+I0222PWgwS7ZZOvn9OST99mFQFE0eKTftOewhi8UIlcyKciKQ/I+f7gDiCLrV6olsserKNNIhn55tUXkuMKxNExtHtG0FmOJt7HtNJI4r1v3T3zfY/tSAu1uLiYdTWp3yuk6lYLjpbK07dVQZ3yTfqf5xb+AS8NHgv4Ea1Vzrgbqc=
  on:
    tags: true
    repo: thombashi/DateTimeRange
  distributions: "sdist bdist_wheel"
