language: python

matrix:
    include:
        - os: linux
          python: 2.7
          sudo: required
          env: TOXENV=python2.7

        - os: linux
          python: 3.4
          sudo: required
          env: TOXENV=python3.4

        - os: linux
          python: 3.5
          sudo: required
          env: TOXENV=python3.5

        - os: linux
          python: 3.6
          sudo: required
          env: TOXENV=python3.6

        - os: linux
          python: 3.7-dev
          sudo: required
          env: TOXENV=python3.7

install:
    - bash -x .travis/install.sh

script:
    - bash -x .travis/run_test.sh

after_success:
    - coveralls

notifications:
    slack:
        secure: NfS1a6caCCDIgC/1MgNqD8e3IR9E5lKn8VA5KsdY8hBxYXHEYxZ52DaX+fIDifW5Pz7QG0NMHUfn5OiAbJOtRDqFLt0DN/cgzMoN4E+obhRzWx6JhYBMHQTE2qe7LnzIqmnWHoYP2K0HUcnyRMp8teIw8To89LwkyVD6G9oMlERCtTGzORpwtqPJKeNrjkDA2fbmlmca4HI0BCbkl8aWVfNvdEka/z09s/XzkMYbuhpJWnyFfARDQS5zmdZCEtWUbQbQsWvl9z+d2JISgzYzrQOIV9f8BFZTvPq6KUlsnPpR8O3nBr5Q61i51awd8HhH6zjn8jKoJVLdrjt1HPSWgWZx/BUqGKBa6PVrkZVwOQx+eNYyCIYEv38ViYAayO6c5Yt/LCsNg2h4Nyl6UM7OwTEN6Z+L1+ke70mWnmRHvYdIBbszvkF6H6BRF+1Yj//Yr7fx33yXzKEhIIyZ94zbwu6YqdPhuROSIHv5lCe5+dT8uYWNNF0QH46GcWC9/2kapO1ySu3iBOFzPxyDnxaBzzqazARKl/fibpbnMvzyKZnd1moHrWGSePKzF5ynGSxSzxctSf7Da683dl3jmqBUcTsDP7IEcj6LkJCF2/Q8ZexX6Kn0zULP+QNOisdt89gHFjHHA6PUD4g7qWXWsB/8y51HUtW7EiaoLjsAdaAHN8w=
